# Generated by Django 3.0.3 on 2020-03-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('portion', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dish')),
            ],
        ),
    ]
